// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package go_micro_sailing_user

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Status is the 'status' enum type from schema 'sailing_user'.
type Status int32

const (
	// StatusNormal is the 'normal' Status.
	Status_STATUS_NORMAL Status = 0
	// StatusDisable is the 'disable' Status.
	Status_STATUS_DISABLE Status = 1
	// StatusDeleted is the 'deleted' Status.
	Status_STATUS_DELETED Status = 2
)

var Status_name = map[int32]string{
	0: "STATUS_NORMAL",
	1: "STATUS_DISABLE",
	2: "STATUS_DELETED",
}

var Status_value = map[string]int32{
	"STATUS_NORMAL":  0,
	"STATUS_DISABLE": 1,
	"STATUS_DELETED": 2,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

// Type is the 'type' enum type from schema 'sailing_user'.
type Type int32

const (
	// TypeDefault is the 'default' Type.
	Type_TYPE_DEFAULT Type = 0
	// TypeOfficial is the 'official' Type.
	Type_TYPE_OFFICIAL Type = 1
	// TypeMerchant is the 'merchant' Type.
	Type_TYPE_MERCHANT Type = 2
)

var Type_name = map[int32]string{
	0: "TYPE_DEFAULT",
	1: "TYPE_OFFICIAL",
	2: "TYPE_MERCHANT",
}

var Type_value = map[string]int32{
	"TYPE_DEFAULT":  0,
	"TYPE_OFFICIAL": 1,
	"TYPE_MERCHANT": 2,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}

func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{1}
}

// User represents a row from 'sailing_user.user'.
type User struct {
	Id                   uint64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid                  string               `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Type                 Type                 `protobuf:"varint,3,opt,name=type,proto3,enum=go.micro.sailing.user.Type" json:"type,omitempty"`
	Email                string               `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Mobile               string               `protobuf:"bytes,5,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Avatar               string               `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Nickname             string               `protobuf:"bytes,7,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Username             string               `protobuf:"bytes,8,opt,name=username,proto3" json:"username,omitempty"`
	Password             string               `protobuf:"bytes,9,opt,name=password,proto3" json:"password,omitempty"`
	Salt                 string               `protobuf:"bytes,10,opt,name=salt,proto3" json:"salt,omitempty"`
	Active               bool                 `protobuf:"varint,11,opt,name=active,proto3" json:"active,omitempty"`
	Status               Status               `protobuf:"varint,12,opt,name=status,proto3,enum=go.micro.sailing.user.Status" json:"status,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *User) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_TYPE_DEFAULT
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *User) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *User) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetSalt() string {
	if m != nil {
		return m.Salt
	}
	return ""
}

func (m *User) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *User) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_STATUS_NORMAL
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{1}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

type Request struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Request) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Request) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Response struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	User                 *User    `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Response) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Response) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterEnum("go.micro.sailing.user.Status", Status_name, Status_value)
	proto.RegisterEnum("go.micro.sailing.user.Type", Type_name, Type_value)
	proto.RegisterType((*User)(nil), "go.micro.sailing.user.User")
	proto.RegisterType((*Error)(nil), "go.micro.sailing.user.Error")
	proto.RegisterType((*Request)(nil), "go.micro.sailing.user.Request")
	proto.RegisterType((*Response)(nil), "go.micro.sailing.user.Response")
}

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor_9b283a848145d6b7) }

var fileDescriptor_9b283a848145d6b7 = []byte{
	// 695 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x5d, 0x6e, 0xdb, 0x38,
	0x10, 0xb6, 0xe4, 0x7f, 0x3a, 0x3f, 0x5e, 0x62, 0x13, 0x68, 0xb5, 0xbb, 0xb5, 0xea, 0xa2, 0x80,
	0x11, 0xa0, 0x32, 0xe0, 0xa0, 0x07, 0x90, 0x63, 0x05, 0x35, 0xe0, 0x38, 0x2d, 0x2d, 0x3f, 0xe4,
	0x29, 0xa0, 0x25, 0xda, 0x21, 0x2a, 0x99, 0xae, 0x48, 0xa5, 0x30, 0x7a, 0x82, 0xe6, 0xa9, 0x17,
	0xc8, 0x7d, 0x7a, 0x8a, 0x14, 0xc8, 0x0d, 0x7a, 0x83, 0x82, 0xa4, 0x9c, 0x34, 0x40, 0x5d, 0xa0,
	0x2f, 0x02, 0xbf, 0xf9, 0x3e, 0x0e, 0x67, 0xe6, 0x1b, 0x81, 0x83, 0x55, 0xca, 0x04, 0xeb, 0x66,
	0x9c, 0xa4, 0xea, 0xe3, 0x2a, 0x0c, 0x0f, 0x16, 0xcc, 0x4d, 0x68, 0x98, 0x32, 0x97, 0x63, 0x1a,
	0xd3, 0xe5, 0xc2, 0x95, 0xa4, 0xdd, 0x5a, 0x30, 0xb6, 0x88, 0x49, 0x57, 0x89, 0x66, 0xd9, 0xbc,
	0x2b, 0x68, 0x42, 0xb8, 0xc0, 0xc9, 0x4a, 0xdf, 0xb3, 0x5f, 0x2d, 0xa8, 0xb8, 0xca, 0x66, 0x6e,
	0xc8, 0x92, 0xee, 0x82, 0x2d, 0xd8, 0xa3, 0x52, 0x22, 0xfd, 0x96, 0x3c, 0x69, 0x79, 0xfb, 0x7b,
	0x11, 0x94, 0xa6, 0x9c, 0xa4, 0xf0, 0x10, 0x98, 0x34, 0xb2, 0x0c, 0xc7, 0xe8, 0x94, 0xfa, 0x95,
	0xfb, 0xbb, 0x96, 0x39, 0x1c, 0x20, 0x93, 0x46, 0xf0, 0x1f, 0x50, 0xcc, 0x68, 0x64, 0x99, 0x8e,
	0xd1, 0xa9, 0xf7, 0xab, 0xf7, 0x77, 0xad, 0xe2, 0x74, 0x38, 0x40, 0x32, 0x06, 0xbb, 0xa0, 0x24,
	0xd6, 0x2b, 0x62, 0x15, 0x1d, 0xa3, 0xb3, 0xd7, 0xfb, 0xd7, 0xfd, 0x65, 0xc5, 0x6e, 0xb0, 0x5e,
	0x11, 0xa4, 0x84, 0xf0, 0x6f, 0x50, 0x26, 0x09, 0xa6, 0xb1, 0x55, 0x92, 0xd9, 0x90, 0x06, 0xf0,
	0x10, 0x54, 0x12, 0x36, 0xa3, 0x31, 0xb1, 0xca, 0x2a, 0x9c, 0x23, 0x19, 0xc7, 0xd7, 0x58, 0xe0,
	0xd4, 0xaa, 0xe8, 0xb8, 0x46, 0xd0, 0x06, 0xb5, 0x25, 0x0d, 0xdf, 0x2f, 0x71, 0x42, 0xac, 0xaa,
	0x62, 0x1e, 0xb0, 0xe4, 0xe4, 0xa3, 0x8a, 0xab, 0x69, 0x6e, 0x83, 0x25, 0xb7, 0xc2, 0x9c, 0x7f,
	0x64, 0x69, 0x64, 0xd5, 0x35, 0xb7, 0xc1, 0x10, 0x82, 0x12, 0xc7, 0xb1, 0xb0, 0x80, 0x8a, 0xab,
	0xb3, 0x7a, 0x3f, 0x14, 0xf4, 0x9a, 0x58, 0x0d, 0xc7, 0xe8, 0xd4, 0x50, 0x8e, 0xe0, 0x6b, 0x50,
	0xe1, 0x02, 0x8b, 0x8c, 0x5b, 0x3b, 0xaa, 0xf1, 0xff, 0xb7, 0x34, 0x3e, 0x51, 0x22, 0x94, 0x8b,
	0xe1, 0x09, 0x00, 0x61, 0x4a, 0xb0, 0x20, 0xd1, 0x25, 0x16, 0xd6, 0xae, 0x63, 0x74, 0x1a, 0x3d,
	0xdb, 0xd5, 0x76, 0xba, 0x1b, 0x93, 0xdc, 0x60, 0x63, 0x67, 0xbf, 0xf6, 0xf5, 0xae, 0x55, 0xf8,
	0xf2, 0xad, 0x65, 0xa0, 0x7a, 0x7e, 0xcf, 0x13, 0x32, 0x49, 0xb6, 0x8a, 0x36, 0x49, 0xf6, 0xfe,
	0x24, 0x49, 0x7e, 0xcf, 0x13, 0xed, 0x63, 0x50, 0xf6, 0xd3, 0x94, 0xa5, 0xb2, 0xeb, 0x90, 0x45,
	0x44, 0xb9, 0x5e, 0x46, 0xea, 0x2c, 0xbb, 0x8e, 0x88, 0x90, 0x26, 0x99, 0x7a, 0xea, 0x1a, 0xb5,
	0x2f, 0x40, 0x15, 0x91, 0x0f, 0x19, 0xe1, 0x6a, 0x30, 0xb2, 0xc1, 0xa1, 0x5e, 0x97, 0x3a, 0xca,
	0xd1, 0x93, 0xe1, 0x9b, 0xbf, 0x19, 0x7e, 0xf1, 0xe9, 0xf0, 0xdb, 0x9f, 0x0d, 0x50, 0x43, 0x84,
	0xaf, 0xd8, 0x92, 0x13, 0x68, 0x81, 0x2a, 0xcf, 0xc2, 0x90, 0x70, 0xae, 0xb2, 0xd7, 0xd0, 0x06,
	0xc2, 0x1e, 0x28, 0x13, 0x59, 0xb6, 0xca, 0xdd, 0xe8, 0xfd, 0xb7, 0x65, 0xec, 0xaa, 0x35, 0xa4,
	0xa5, 0x72, 0x45, 0x65, 0x50, 0x3d, 0xd9, 0xd8, 0xba, 0xa2, 0xf2, 0x07, 0x40, 0x4a, 0x78, 0xf4,
	0x09, 0x54, 0xb4, 0x6f, 0xf0, 0x05, 0xd8, 0x9d, 0x04, 0x5e, 0x30, 0x9d, 0x5c, 0x8e, 0xcf, 0xd1,
	0x99, 0x37, 0x6a, 0x16, 0xec, 0xe6, 0xcd, 0xad, 0xb3, 0xa3, 0xe9, 0x31, 0x4b, 0x13, 0x1c, 0xc3,
	0x97, 0x60, 0x2f, 0x17, 0x0d, 0x86, 0x13, 0xaf, 0x3f, 0xf2, 0x9b, 0x86, 0xfd, 0xd7, 0xcd, 0xad,
	0xb3, 0xab, 0x55, 0x03, 0xca, 0xf1, 0x2c, 0x26, 0x3f, 0xcb, 0xfc, 0x91, 0x1f, 0xf8, 0x83, 0xa6,
	0xf9, 0x44, 0x46, 0x62, 0x22, 0x48, 0x74, 0xc4, 0x41, 0x49, 0xfe, 0x2d, 0xf0, 0x39, 0xd8, 0x09,
	0x2e, 0xde, 0xfa, 0x97, 0x03, 0xff, 0xd4, 0x9b, 0x8e, 0x82, 0x66, 0xc1, 0xde, 0xbf, 0xb9, 0x75,
	0x1a, 0x92, 0x1b, 0x90, 0x39, 0xce, 0x62, 0x21, 0xab, 0x53, 0x92, 0xf3, 0xd3, 0xd3, 0xe1, 0xc9,
	0xd0, 0x1b, 0x35, 0x0d, 0x5d, 0x9d, 0xd4, 0x9c, 0xcf, 0xe7, 0x34, 0xa4, 0x38, 0x7e, 0x10, 0x9d,
	0xf9, 0xe8, 0xe4, 0x8d, 0x37, 0x0e, 0x9a, 0xe6, 0xa3, 0xe8, 0x8c, 0xa4, 0xe1, 0x15, 0x5e, 0x8a,
	0x5e, 0x08, 0x1a, 0xb2, 0xff, 0x09, 0x49, 0xaf, 0x69, 0x48, 0x60, 0x00, 0xf6, 0xdf, 0x65, 0x24,
	0x5d, 0xcb, 0x58, 0x7f, 0x3d, 0x96, 0xde, 0x3d, 0xdb, 0x32, 0xb6, 0x7c, 0x1f, 0xec, 0xd6, 0x56,
	0x5e, 0x7b, 0xda, 0x2e, 0xcc, 0x2a, 0x6a, 0x37, 0x8f, 0x7f, 0x04, 0x00, 0x00, 0xff, 0xff, 0x69,
	0xde, 0x97, 0x27, 0xed, 0x04, 0x00, 0x00,
}
