// Code generated by protoc-gen-go. DO NOT EDIT.
// source: biz/proto/user.proto

package sailing_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserType int32

const (
	User_default  UserType = 0
	User_official UserType = 1
	User_merchant UserType = 2
)

var UserType_name = map[int32]string{
	0: "default",
	1: "official",
	2: "merchant",
}

var UserType_value = map[string]int32{
	"default":  0,
	"official": 1,
	"merchant": 2,
}

func (x UserType) String() string {
	return proto.EnumName(UserType_name, int32(x))
}

func (UserType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fc8547c9b39c1a43, []int{0, 0}
}

type User struct {
	Id                   uint64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid                  string               `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Email                string               `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Mobile               string               `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Avatar               string               `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Nickname             string               `protobuf:"bytes,6,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Username             string               `protobuf:"bytes,7,opt,name=username,proto3" json:"username,omitempty"`
	Password             string               `protobuf:"bytes,8,opt,name=password,proto3" json:"password,omitempty"`
	Salt                 string               `protobuf:"bytes,9,opt,name=salt,proto3" json:"salt,omitempty"`
	Active               bool                 `protobuf:"varint,10,opt,name=active,proto3" json:"active,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,11,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,12,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,13,opt,name=deletedAt,proto3" json:"deletedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc8547c9b39c1a43, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *User) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *User) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetSalt() string {
	if m != nil {
		return m.Salt
	}
	return ""
}

func (m *User) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *User) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc8547c9b39c1a43, []int{1}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

type Request struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc8547c9b39c1a43, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Request) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Request) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Response struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	User                 *User    `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc8547c9b39c1a43, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Response) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Response) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterEnum("sailing.user.UserType", UserType_name, UserType_value)
	proto.RegisterType((*User)(nil), "sailing.user.user")
	proto.RegisterType((*Error)(nil), "sailing.user.Error")
	proto.RegisterType((*Request)(nil), "sailing.user.Request")
	proto.RegisterType((*Response)(nil), "sailing.user.Response")
}

func init() { proto.RegisterFile("biz/proto/user.proto", fileDescriptor_fc8547c9b39c1a43) }

var fileDescriptor_fc8547c9b39c1a43 = []byte{
	// 462 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0xdd, 0xa4, 0x49, 0x9b, 0x4e, 0x0a, 0x54, 0x66, 0x59, 0x59, 0xbd, 0x50, 0xe5, 0x80, 0xca,
	0x25, 0x95, 0xba, 0x17, 0xae, 0xac, 0xc4, 0x01, 0x0e, 0x48, 0x58, 0x70, 0xe0, 0xe8, 0xc6, 0xd3,
	0x62, 0x91, 0xc4, 0xc1, 0x76, 0x76, 0x55, 0xfe, 0x91, 0x7f, 0x42, 0xb6, 0x93, 0x42, 0x39, 0xb0,
	0x97, 0x68, 0xde, 0xcc, 0x7b, 0xc9, 0xe4, 0xbd, 0x81, 0xeb, 0xbd, 0xfc, 0xb9, 0xed, 0xb4, 0xb2,
	0x6a, 0xdb, 0x1b, 0xd4, 0xa5, 0x2f, 0xc9, 0xc2, 0x70, 0x59, 0xcb, 0xf6, 0x58, 0xba, 0xde, 0xea,
	0xe5, 0x51, 0xa9, 0x63, 0x8d, 0x81, 0xb6, 0xef, 0x0f, 0x5b, 0x2b, 0x1b, 0x34, 0x96, 0x37, 0x5d,
	0xa0, 0x17, 0xbf, 0x26, 0x90, 0x38, 0x26, 0x79, 0x0a, 0xb1, 0x14, 0x34, 0x5a, 0x47, 0x9b, 0x84,
	0xc5, 0x52, 0x90, 0x25, 0x4c, 0x7a, 0x29, 0x68, 0xbc, 0x8e, 0x36, 0x73, 0xe6, 0x4a, 0x72, 0x0d,
	0x29, 0x36, 0x5c, 0xd6, 0x74, 0xe2, 0x7b, 0x01, 0x90, 0x1b, 0x98, 0x36, 0x6a, 0x2f, 0x6b, 0xa4,
	0x89, 0x6f, 0x0f, 0xc8, 0xf5, 0xf9, 0x3d, 0xb7, 0x5c, 0xd3, 0x34, 0xf4, 0x03, 0x22, 0x2b, 0xc8,
	0x5a, 0x59, 0x7d, 0x6f, 0x79, 0x83, 0x74, 0xea, 0x27, 0x67, 0xec, 0x66, 0x6e, 0x17, 0x3f, 0x9b,
	0x85, 0xd9, 0x88, 0xdd, 0xac, 0xe3, 0xc6, 0x3c, 0x28, 0x2d, 0x68, 0x16, 0x66, 0x23, 0x26, 0x04,
	0x12, 0xc3, 0x6b, 0x4b, 0xe7, 0xbe, 0xef, 0x6b, 0xff, 0xfd, 0xca, 0xca, 0x7b, 0xa4, 0xb0, 0x8e,
	0x36, 0x19, 0x1b, 0x10, 0x79, 0x03, 0xf3, 0x4a, 0x23, 0xb7, 0x28, 0xde, 0x5a, 0x9a, 0xaf, 0xa3,
	0x4d, 0xbe, 0x5b, 0x95, 0xc1, 0xa5, 0x72, 0x74, 0xa9, 0xfc, 0x3c, 0xba, 0xc4, 0xfe, 0x90, 0x9d,
	0xb2, 0xef, 0xc4, 0xa0, 0x5c, 0x3c, 0xae, 0x3c, 0x93, 0x9d, 0x52, 0x60, 0x8d, 0x41, 0xf9, 0xe4,
	0x71, 0xe5, 0x99, 0x5c, 0x6c, 0x21, 0xb1, 0xa7, 0x0e, 0x49, 0x0e, 0x33, 0x81, 0x07, 0xde, 0xd7,
	0x76, 0x79, 0x45, 0x16, 0x90, 0xa9, 0xc3, 0x41, 0x56, 0x92, 0xd7, 0xcb, 0xc8, 0xa1, 0x06, 0x75,
	0xf5, 0x8d, 0xb7, 0x76, 0x19, 0x17, 0xb7, 0x90, 0xbe, 0xd3, 0x5a, 0x69, 0xe7, 0x49, 0xa5, 0x04,
	0xfa, 0x44, 0x53, 0xe6, 0x6b, 0xe7, 0x89, 0x40, 0xeb, 0x22, 0x0c, 0xb1, 0x0e, 0xa8, 0xf8, 0x0a,
	0x33, 0x86, 0x3f, 0x7a, 0x34, 0xde, 0x36, 0x67, 0xf9, 0xfb, 0x70, 0x0a, 0x73, 0x36, 0xa0, 0x8b,
	0x68, 0xe2, 0xff, 0x44, 0x33, 0xb9, 0x8c, 0xa6, 0x78, 0x80, 0x8c, 0xa1, 0xe9, 0x54, 0x6b, 0x90,
	0x50, 0x98, 0x99, 0xbe, 0xaa, 0xd0, 0x18, 0xff, 0xf2, 0x8c, 0x8d, 0x90, 0xbc, 0x86, 0x14, 0xdd,
	0xd6, 0xfe, 0xd5, 0xf9, 0xee, 0x79, 0xf9, 0xf7, 0x11, 0x97, 0xfe, 0x87, 0x58, 0x60, 0x90, 0x57,
	0xe1, 0x5e, 0xfd, 0x87, 0xf2, 0x1d, 0xb9, 0x64, 0xba, 0x07, 0xf3, 0xf3, 0xdd, 0x07, 0x48, 0xbe,
	0xb8, 0xbb, 0xbe, 0x83, 0x67, 0x9f, 0x7a, 0xd4, 0x27, 0x07, 0xee, 0x4e, 0x1f, 0xdd, 0xbe, 0x2f,
	0x2e, 0x45, 0xc3, 0xaf, 0xaf, 0x6e, 0xfe, 0x6d, 0x87, 0xb5, 0x8b, 0xab, 0xfd, 0xd4, 0x87, 0x74,
	0xfb, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x2f, 0x1b, 0x1f, 0xff, 0x72, 0x03, 0x00, 0x00,
}
